"""Napkin back-projection of the idle airflow requirement to cold coolant temperatures (2026-09-20).
Inputs are named at the top; every number is either a measured anchor from fullchannels.csv (09-19) or a
labelled assumption. Output: requirement.md beside this script."""
import numpy as np, io, sys, datetime as dt
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
# ---- measured anchors (clean TB, new TPS frame, window 1.5-6.5, table spark 18 deg) ----
S_HOT = 2.9          # % TPS sustaining 1025 rpm at CLT>=96, first minutes hot (oil ~2.8-3.0 bar)  [tb_clean note §8]
S_SOAK = 2.43        # same, 15 min soaked (oil ~2.1 bar)
MASS_35 = 1.15       # mass/rev at CLT 35 vs early-hot: MAP 37/35 x density (331/303) — measured at +8 deg spark
SPARK_35 = 8.0       # deg of ignition-PID advance the CLT-35 rows carried above the 18.5 target
DAIR_PER_DEG = 0.025 # air per degree of spark near idle target (repo note: +6 deg => +15 % air)  [assumption]
S_35_MEAS = 3.76     # normalised sustaining TPS (x1025/N) at CLT 35, dirty rows converted to clean frame
T_OIL_35 = 32.0      # oil temp at those samples: 35-64 s after a crank at CLT 32 = ambient   [assumption]
T_OIL_HOT = 80.0     # oil temp at the early-hot anchor (OP/N 3.0 bar/krpm → μ ≈ 1.8× soaked; oil note R4 maps that to ~80 °C)   [inferred]
R_OIL = 0.7          # oil warms this fraction as fast as coolant on a cold start (OP-inferred 80 C at CLT 95 from a 30 C start -> 0.77)
KV40, KV100 = 70.0, 10.5   # 10W-30 typical kinematic viscosity, cSt                            [model knowledge]
FRICTION_EXP = 0.3   # rubbing friction ∝ mu^0.3 (Heywood, cited in oil note R4)
WIN_LO, WIN_HI = 1.5, 6.5  # idleDBWTargetMin/Max, 09-19 19:05 export (raw 15 / 65)
PID_OUT_MIN, PID_INT_MIN = -25, -25   # airflow-%; export 09-19 19:05
CLT_TABLE = [0, 15, 30, 45, 60, 75, 96, 105]
TARGETS = [1000, 1250, 1500, 1750, 2000]
EXPORT = {1000:[56,53.5,49.5,45,40.5,35.5,28,28],1250:[57.5,55.5,51,46.5,42,37.5,33,31.5],1500:[60,58,53.5,49.5,45.5,40.5,36.5,35],
          1750:[62.5,60.5,56.5,52.5,48.5,44,40,38.5],2000:[63.5,61.5,57.5,54,50,45.5,41.5,40]}   # idleActiveAirflow, 09-19 19:05 export, x0.5 applied
PROP8 = {1000:[57.5,50.5,43.5,37.5,34,30,26.5,26.5],1250:[79.5,70.5,62,54,50,45,40.5,40.5],1500:[100,90.5,80.5,71,66,60,55,55],
         1750:[100,100,98.5,88,82,75,69,69],2000:[100,100,100,100,98,90,83,83]}                 # tb_clean note §8 proposal
def idle_rpm(clt):   # idleRPM vs cltBins (-40..110 step 10), export 09-19
    bins=list(range(-40,111,10)); vals=[1500]*10+[1450,1300,1150,1025,1025,1025]
    return float(np.interp(clt,bins,vals))
# ---- viscosity: Walther / ASTM D341 through the two 10W-30 points ----
def walther_fit(k40,k100):
    T1,T2=313.15,373.15; Z=lambda v: np.log10(np.log10(v+0.7))
    B=(Z(k40)-Z(k100))/(np.log10(T2)-np.log10(T1)); A=Z(k40)+B*np.log10(T1); return A,B
A_W,B_W=walther_fit(KV40,KV100)
def kv(tc): return 10**(10**(A_W-B_W*np.log10(tc+273.15)))-0.7
def mu_rel(t_oil): return kv(t_oil)/kv(T_OIL_HOT)
# ---- calibrate the rubbing share b from the CLT-35 measurement ----
D35 = MASS_35*(1+SPARK_35*DAIR_PER_DEG)              # mass demand at table spark, CLT 35 / oil 32
g35 = mu_rel(T_OIL_35)**FRICTION_EXP
b = (D35-1)/(g35-1); a = 1-b                          # D = a + b*(mu_rel^0.3)
def demand(t_oil): return a + b*mu_rel(t_oil)**FRICTION_EXP
# ---- throttle-body flow coefficient vs CLT (bore/plate clearance closes cold) ----
K35 = MASS_35/(S_35_MEAS/S_HOT)                       # implied k(35)/k(hot-early)
k_slope = (1-K35)/(95-35)
def K(clt): return 1 - k_slope*(95-clt)
# ---- model L (low bound): empirical power law in oil viscosity through the two clean-frame warm-up points ----
S60_CLEAN, T_OIL_60 = 3.20, 53.0      # clean TB, CLT 55-60, 1450 rpm, table spark, restart from CLT 51 (oil ~ CLT)
P_L = np.log(S_35_MEAS/S_HOT)/np.log(mu_rel(T_OIL_35))     # fits CLT-35 as logged (ign PID +8 deg included)
def tps_req_L(N, clt, t_amb):
    t_oil = t_amb + R_OIL*(clt-t_amb)
    return S_HOT*(N/1025.0)*mu_rel(t_oil)**P_L*np.sqrt((t_amb+273.15)/303.15), t_oil
def tps_req(N, clt, t_amb, spark_help=0.0):
    t_oil = t_amb + R_OIL*(clt-t_amb)
    D = demand(t_oil)*(1-spark_help*DAIR_PER_DEG)
    dens = np.sqrt((t_amb+273.15)/303.15)             # choked plate passes more mass in cold air
    return S_HOT*(N/1025.0)*D*dens/K(clt), t_oil, D
def air_pct(tps): return (tps-WIN_LO)/(WIN_HI-WIN_LO)*100
def cell(tbl, N, clt):
    row=np.array([np.interp(N,TARGETS,[tbl[t][j] for t in TARGETS]) for j in range(len(CLT_TABLE))])
    return float(np.interp(clt,CLT_TABLE,row))
chk_H,_,_=tps_req(1450,60,51); chk_L,_=tps_req_L(1450,60,51)
L=[f"# Idle airflow requirement back-projected to cold — napkin model ({dt.date.today()})\n",
   "Generated by `backproject.py`. Anchors: clean TB, 1.5–6.5 window, 09-19 `fullchannels.csv`. See the canonical note for the derivation and the assumptions list.\n",
   f"Calibration: D(oil 32 °C) = {D35:.2f} (mass/rev at table spark vs early-hot) → rubbing share b = {b:.2f}, fixed share a = {a:.2f}; "
   f"K(CLT) = 1 − {k_slope:.4f}·(95 − CLT) (K(35) = {K35:.3f}). Model L exponent p = {P_L:.3f}. "
   f"**Check against the clean CLT-60 / 1450 rpm measurement (3.20 × 1450/1025 = 4.53 % TPS, table spark):** model H {chk_H:.2f}, model L {chk_L:.2f}. 10W-30 Walther: KV(0) = {kv(0):.0f}, KV(−10) = {kv(-10):.0f}, KV(30) = {kv(30):.0f}, KV(105) = {kv(105):.1f} cSt.\n",
   "## Viscosity → demand multiplier (mass per rev at table spark, vs early-hot)\n",
   "| oil °C | −20 | −10 | 0 | 10 | 20 | 30 | 45 | 60 | 80 | 105 |","|---|"+"---|"*10,
   "| μ/μ_hot | "+" | ".join(f"{mu_rel(t):.0f}" for t in [-20,-10,0,10,20,30,45,60,80,105])+" |",
   "| D | "+" | ".join(f"{demand(t):.2f}" for t in [-20,-10,0,10,20,30,45,60,80,105])+" |",
   "\n## Requirement along the `idleRPM` warm-up path, per start temperature\n",
   "TPS_req = S_hot × N/1025 × D(oil) × √(T_amb/30 °C) / K(CLT); oil = amb + 0.7·(CLT − amb). Airflow-% in the 1.5–6.5 window. "
   "`ign+8` = the same with the ignition PID carrying +8° (what the 09-19 morning actually did).\n",
   "| start amb °C | CLT cell | target | oil °C | D | K | TPS req H (18°) | TPS req L (ign helps) | air-% req H / L | export cell | export − req H/L | §8 cell | §8 − req H/L |",
   "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
worst={}
for amb in [-20,-10,0,10,20,30]:
    for clt in [c for c in [-20,-10,0,15,30,45,60,75,96] if c>=amb]:
        N=idle_rpm(clt); tps,toil,D=tps_req(N,clt,amb); tpsL,_=tps_req_L(N,clt,amb)
        ex=cell(EXPORT,N,max(clt,0)); p8=cell(PROP8,N,max(clt,0)); req=air_pct(tps); reqL=air_pct(tpsL)
        L.append(f"| {amb} | {clt} | {N:.0f} | {toil:.0f} | {D:.2f} | {K(clt):.2f} | **{tps:.2f}** | **{tpsL:.2f}** | {req:.0f} / {reqL:.0f} | {ex:.0f} | {ex-req:+.0f} / {ex-reqL:+.0f} | {p8:.0f} | {p8-req:+.0f} / {p8-reqL:+.0f} |")
        key=max(clt,0)
        if key not in worst or tps>worst[key][0]: worst[key]=(tps,amb,N,tpsL)
L+=["\n## Worst case per table column (coldest start that passes through it, −20 °C considered)\n",
    "| CLT column | from start | target | TPS req L … H | air-% req L … H | export cell | export − req (L / H) | §8 cell | §8 − req (L / H) | ceiling to hold req H + 5 air-% |",
    "|---|---|---|---|---|---|---|---|---|---|"]
for c in [0,15,30,45,60,75,96]:
    tps,amb,N,tpsL=worst[c]; req=air_pct(tps); reqL=air_pct(tpsL); ex=cell(EXPORT,N,c); p8=cell(PROP8,N,c)
    L.append(f"| {c} | {amb} | {N:.0f} | **{tpsL:.2f} … {tps:.2f}** | {reqL:.0f} … {req:.0f} | {ex:.0f} | {ex-reqL:+.0f} / {ex-req:+.0f} | {p8:.0f} | {p8-reqL:+.0f} / {p8-req:+.0f} | {tps+0.25:.1f} % TPS |")
L+=[f"\nPID band for 'over-air and let the PID pull it down': cell − requirement should sit between about **+5 and +20 airflow-%** "
    f"(+0.25…+1.0 % TPS): below +5 the integral has to *add* and the +15 `idleAirFlowIntegralLimitMax` is the first thing that binds; "
    f"above ~+20 the −25 `idleAirPIDOutMin` / integral clamp binds and the idle hangs high.\n"]
open("requirement.md","w",encoding="utf-8").write("\n".join(L)+"\n"); print("\n".join(L))
